package api

import cats.effect.IO
import org.http4s.HttpRoutes
import sttp.tapir.server.ServerEndpoint
import sttp.tapir.server.http4s.Http4sServerInterpreter
import sttp.tapir.swagger.bundle.SwaggerInterpreter

object HttpApi:

  // 1) Endpoint descriptions (contracts only)
  // These are used for docs generation and as your "API spec".
  private val endpointDescriptions =
    List(Endpoints.health)

  // 2) Business server endpoints (contracts + logic)
  // The real, runnable endpoints.
  private val businessServerEndpoints: List[ServerEndpoint[Any, IO]] =
    List(
      Endpoints.health.serverLogicSuccess[IO](_ => IO.pure("ok"))
    )

  // Docs server endpoints (generated by tapir from the endpoint descriptions)
  private val docsServerEndpoints: List[ServerEndpoint[Any, IO]] =
    SwaggerInterpreter()
      .fromEndpoints[IO](endpointDescriptions, "Streaming Platform Project", "0.1")

  // Combine everything into http4s routes
  val routes: HttpRoutes[IO] =
    Http4sServerInterpreter[IO]()
      .toRoutes(businessServerEndpoints ++ docsServerEndpoints)
